export const BUILTIN = [
  { name: '벤치프레스', met: 5, type: 'weight' },
  { name: '스쿼트', met: 5, type: 'weight' },
  { name: '데드리프트', met: 6, type: 'weight' },
  { name: '숄더프레스', met: 5, type: 'weight' },
  { name: '랫풀다운', met: 4, type: 'weight' },
  { name: '바벨로우', met: 5, type: 'weight' },
  { name: '레그프레스', met: 5, type: 'weight' },
  { name: '레그컬', met: 4, type: 'weight' },
  { name: '레그익스텐션', met: 4, type: 'weight' },
  { name: '덤벨컬', met: 4, type: 'weight' },
  { name: '트라이셉스 익스텐션', met: 4, type: 'weight' },
  { name: '크런치', met: 4, type: 'weight' },
  { name: '플랭크', met: 3, type: 'weight' },
  { name: '런지', met: 5, type: 'weight' },
  { name: '힙쓰러스트', met: 5, type: 'weight' },
  { name: '러닝', met: 8, type: 'cardio' },
  { name: '걷기', met: 3.5, type: 'cardio' },
  { name: '사이클', met: 7, type: 'cardio' },
  { name: '로잉머신', met: 7, type: 'cardio' },
  { name: '스텝밀', met: 9, type: 'cardio' },
]
